apiVersion: apps/v1
kind: deployment
metadata:
  name: app4-deployment
  labels:
    app: app4
    type: fe

spec:
  replicas: 2
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      name: app4-pod
      labels:
        app: app4
        type: fe
    spec:
      containers:
      - name: nginx-containers
        image: nginx
