apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dagr6-deployment
  name: dagr6-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dagr6-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dagr6-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
