apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: dagr10
  name: dagr10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagr10
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dagr10
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
