apiVersion: apps/v1
kind: Deployment
metadata:
  name: app5-deployment
  labels:
    app: app5
    type: fe
spec:
  replicas: 2
    selector:
      matchLabels:
        app: app5
  template:

    metadata:
      name: app5
      labels: app5-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
