apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: myapp2
    type: fe

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp2
        type: fe
    spec:
      containers:
      - name: nginx-container
        image: nginx

replicas: 3

selector:
  matchLabels:
    type: fe
